name: CI/CD
run-name: ${{ github.actor }} 🚀
on:
  push:
    branches: [ develop ]
    pull_request:
      branches: [ develop ]
jobs:
  Build-Testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Build bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build:prod` command